package es.alejandro12120.igor.commands;

import es.alejandro12120.igor.Igor;
import es.alejandro12120.igor.utils.Common;
import net.dv8tion.jda.core.EmbedBuilder;
import net.dv8tion.jda.core.events.message.guild.GuildMessageReceivedEvent;
import net.dv8tion.jda.core.hooks.ListenerAdapter;

public class InfoCMD extends ListenerAdapter {

	@Override
	public void onGuildMessageReceived(GuildMessageReceivedEvent e) {
		String[] args = e.getMessage().getContentRaw().split("\\s+");

		if (args[0].equalsIgnoreCase(Igor.getIgor().prefix + "info")) {
			String version = Common.getFortniteVersion();

			String total = String.valueOf(Common.getTotalPakCount());
			String encrypted = String.valueOf(Common.getEncryptedPakCount());
			EmbedBuilder embd = new EmbedBuilder();

			embd.setTitle("Fortnite `V" + version + "`");
			embd.setDescription("All Fortnite's information.");
			embd.addField("Total Pak Count: ", "`" + total + "`", true);
			embd.addField("Encrypted Pak Count", "`" + encrypted + "`", true);
			embd.setFooter("Generated by Igor.", "https://pbs.twimg.com/profile_images/1017458813199372289/QtGv1tyn_400x400.jpg");
			embd.setColor(0x00ffff);
			e.getChannel().sendMessage(embd.build()).queue();
			embd.clear();

		}
	}

}
