package es.alejandro12120.igor.commands;

import es.alejandro12120.igor.Igor;
import java.util.Date;
import net.dv8tion.jda.core.EmbedBuilder;
import net.dv8tion.jda.core.entities.Message;
import net.dv8tion.jda.core.events.message.guild.GuildMessageReceivedEvent;
import net.dv8tion.jda.core.hooks.ListenerAdapter;
import twitter4j.Trend;
import twitter4j.Trends;
import twitter4j.TwitterException;

public class TrendingTopicsCMD extends ListenerAdapter {

	public static String trending_id;
	public static int code;
	
	@Override
	public void onGuildMessageReceived(GuildMessageReceivedEvent e) {
		String[] args = e.getMessage().getContentRaw().split("\\s+");
		if (args[0].equalsIgnoreCase(Igor.getIgor().prefix + "tt")) {
			if (args.length == 1) {
				try {
					Trends trends = Igor.getIgor().getTrendingTwitter().getPlaceTrends(1);
					int count = 0;
					String description = "";
					for (Trend trend : trends.getTrends()) {
						if (count != 0 && count < 6) {
							description = description + count + ". " + trend.getName() + " \n";
						}
						count++;
					}
					EmbedBuilder embed = new EmbedBuilder();

					embed.setTitle("Global Trends");
					embed.setDescription(description);
					embed.setFooter("Generated by Igor.", Igor.jda.getSelfUser().getAvatarUrl());
					embed.setTimestamp(new Date().toInstant());
					embed.setColor(0x9DF10A);

					Message message = e.getChannel().sendMessage(embed.build()).complete();

					message.addReaction("⬆").queue();

					e.getChannel().sendMessage(message);
					trending_id = message.getId();
					code = 1;
				} catch (TwitterException ex) {
					e.getChannel().sendMessage("ERROR").queue();
				}
			}
			if (args.length == 2) {
				if (args[1].equalsIgnoreCase("spain") || args[1].equalsIgnoreCase("madrid")) {
					try {
						Trends trends = Igor.getIgor().getTrendingTwitter().getPlaceTrends(766273);
						int count = 0;
						String description = "";
						for (Trend trend : trends.getTrends()) {
							if (count != 0 && count < 6) {
								description = description + count + ". " + trend.getName() + " \n";
							}
							count++;
						}
						EmbedBuilder embed = new EmbedBuilder();

						embed.setTitle("Spain Trends");
						embed.setDescription(description);
						embed.setFooter("Generated by Igor.", Igor.jda.getSelfUser().getAvatarUrl());
						embed.setTimestamp(new Date().toInstant());
						embed.setColor(0x9DF10A);

						Message message = e.getChannel().sendMessage(embed.build()).complete();

						message.addReaction("⬆").queue();

						e.getChannel().sendMessage(message);
						trending_id = message.getId();
						code = 766273;
					} catch (TwitterException ex) {
						e.getChannel().sendMessage("ERROR").queue();
					}
				} else if (args[1].equalsIgnoreCase("global") || args[1].equalsIgnoreCase("ww") || args[1].equalsIgnoreCase("worldwide")) {
					try {
						Trends trends = Igor.getIgor().getTrendingTwitter().getPlaceTrends(1);
						int count = 0;
						String description = "";
						for (Trend trend : trends.getTrends()) {
							if (count != 0 && count < 6) {
								description = description + count + ". " + trend.getName() + " \n";
							}
							count++;
						}
						EmbedBuilder embed = new EmbedBuilder();

						embed.setTitle("Global Trends");
						embed.setDescription(description);
						embed.setFooter("Generated by Igor.", Igor.jda.getSelfUser().getAvatarUrl());
						embed.setTimestamp(new Date().toInstant());
						embed.setColor(0x9DF10A);

						Message message = e.getChannel().sendMessage(embed.build()).complete();

						message.addReaction("⬆").queue();

						e.getChannel().sendMessage(message);
						trending_id = message.getId();
						code = 1;
					} catch (TwitterException ex) {
						e.getChannel().sendMessage("ERROR").queue();
					}
				} else {
					e.getChannel().sendMessage("Available locations: spain, global.").queue();
				}
			}

		}
	}

}
